### PR TITLE
Milestone1 : Prepare data architecture documentation 🚀 

### PR DESCRIPTION
**Pull request by JasemDuncan**
In this project, we are going to create a Social Media App called "Stay in touch" 👐.

So, for this first milestone ✔️, we created the Entity Relationship Diagram, located inside the docs folders in the root of the protect. We use LucidChart to create this Diagram. This Diagram explains all the relationships 🔗  between the tables in the database.

🤖  
Kingsley & Jasem.

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### Hi @JasemDuncan and @KingsleyMcSimon :clap: :clap:
#### Good job :+1: However, there is a minor adjustment you need to implement before this project can be approved.

- **_User table should have an `image_link` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_**

#### _Reviewed by Temitayo Adeleke_

**Comment by JasemDuncan** [comment]
Screen Shot 2020-10-19 at 12 23 39

Hello @lekegitrepo 
Thanks for your fast answer, but we will store the "image_link", inside the "infouser" table in the field "gravatar_url". Would it be ok like that?

Thank you,
@JasemDuncan

**Review by kubilaycaglayan — APPROVED** [review]
Hello Team 👋
Status: Project Approved :green_circle: 

Great job! 
You have great attention to the details! :+1:  :blush: 

💡 There's nothing wrong with keeping the image_link in another table with the other user-related information altogether. And this is a good practice actually, called `standardization` in SQL.

😇 In addition to this, if you check the `schema.rb` file, you will see that users table already built.

I am approving the project because I can see that you have enough knowledge to implement the ERD in a good way. 👏👍

👉 For the next milestones and projects please try to stick to the requirements, and if you want to implement a feature in a different way please provide information beforehand. 😊

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

**Comment by JasemDuncan** [comment]
Hello **kubilaycaglayan**

Thank you for your concernt. We are going to stick more to the requirements.

Thank you again,

@JasemDuncan

**Pull request merged**
